// New Dominos
const dominos = [
    {
        "index": 27,
        "sideA": 6,
        "sideB": 6,
        "isDouble": true,
        "edgeL": 12,
        "edgeR": 12,
        "isHorizontal": false,
        "openSideA": false,
        "openSideB": false,
        "openEdgeA": true,
        "openEdgeB": true,
        "totalValue": 12,
        "isFaceUp": true,
        "next": null,
        "image": "http://localhost:8080/images/dom6.6.png",
    },
    {
        "index": 26,
        "sideA": 5,
        "sideB": 6,
        "isDouble": false,
        "edgeL": null,
        "edgeR": null,
        "isHorizontal": false,
        "openSideA": true,
        "openSideB": true,
        "openEdgeA": false,
        "openEdgeB": false,
        "totalValue": 11,
        "isFaceUp": true,
        "next": null,
        "image": "http://localhost:8080/images/dom5.6.png",
    },
    {
        "index": 25,
        "sideA": 5,
        "sideB": 5,
        "isDouble": true,
        "edgeL": 10,
        "edgeR": 10,
        "isHorizontal": false,
        "openSideA": false,
        "openSideB": false,
        "openEdgeA": true,
        "openEdgeB": true,
        "totalValue": 10,
        "isFaceUp": true,
        "next": null,
        "image": "http://localhost:8080/images/dom5.5.png",
    },
    {
        "index": 24,
        "sideA": 4,
        "sideB": 6,
        "isDouble": false,
        "edgeL": null,
        "edgeR": null,
        "isHorizontal": false,
        "openSideA": true,
        "openSideB": true,
        "openEdgeA": false,
        "openEdgeB": false,
        "totalValue": 10,
        "isFaceUp": true,
        "next": null,
        "image": "http://localhost:8080/images/dom4.6.png",
    },

    {
        "index": 23,
        "sideA": 4,
        "sideB": 5,
        "isDouble": false,
        "edgeL": null,
        "edgeR": null,
        "isHorizontal": false,
        "openSideA": true,
        "openSideB": true,
        "openEdgeA": false,
        "openEdgeB": false,
        "totalValue": 9,
        "isFaceUp": true,
        "next": null,
        "image": "http://localhost:8080/images/dom4.5.png",
    },
    {
        "index": 22,
        "sideA": 4,
        "sideB": 4,
        "isDouble": true,
        "edgeL": 8,
        "edgeR": 8,
        "isHorizontal": false,
        "openSideA": false,
        "openSideB": false,
        "openEdgeA": true,
        "openEdgeB": true,
        "totalValue": 8,
        "isFaceUp": true,
        "next": null,
        "image": "http://localhost:8080/images/dom4.4.png",
    },
    {
        "index": 21,
        "sideA": 3,
        "sideB": 6,
        "isDouble": false,
        "edgeL": null,
        "edgeR": null,
        "isHorizontal": false,
        "openSideA": true,
        "openSideB": true,
        "openEdgeA": false,
        "openEdgeB": false,
        "totalValue": 9,
        "isFaceUp": true,
        "next": null,
        "image": "http://localhost:8080/images/dom3.6.png",
    },
    {
        "index": 20,
        "sideA": 3,
        "sideB": 5,
        "isDouble": false,
        "edgeL": null,
        "edgeR": null,
        "isHorizontal": false,
        "openSideA": true,
        "openSideB": true,
        "openEdgeA": false,
        "openEdgeB": false,
        "totalValue": 8,
        "isFaceUp": true,
        "next": null,
        "image": "http://localhost:8080/images/dom3.5.png",
    },
    {
        "index": 19,
        "sideA": 3,
        "sideB": 4,
        "isDouble": false,
        "edgeL": null,
        "edgeR": null,
        "isHorizontal": false,
        "openSideA": true,
        "openSideB": true,
        "openEdgeA": false,
        "openEdgeB": false,
        "totalValue": 7,
        "isFaceUp": true,
        "next": null,
        "image": "http://localhost:8080/images/dom3.4.png",
    },
    {
        "index": 18,
        "sideA": 3,
        "sideB": 3,
        "isDouble": true,
        "edgeL": 6,
        "edgeR": 6,
        "isHorizontal": false,
        "openSideA": false,
        "openSideB": false,
        "openEdgeA": true,
        "openEdgeB": true,
        "totalValue": 6,
        "isFaceUp": true,
        "next": null,
        "image": "http://localhost:8080/images/dom3.3.png",
    },
    {
        "index": 17,
        "sideA": 2,
        "sideB": 6,
        "isDouble": false,
        "edgeL": null,
        "edgeR": null,
        "isHorizontal": false,
        "openSideA": true,
        "openSideB": true,
        "openEdgeA": false,
        "openEdgeB": false,
        "totalValue": 8,
        "isFaceUp": true,
        "next": null,
        "image": "http://localhost:8080/images/dom2.6.png",
    },
    {
        "index": 16,
        "sideA": 2,
        "sideB": 5,
        "isDouble": false,
        "edgeL": null,
        "edgeR": null,
        "isHorizontal": false,
        "openSideA": true,
        "openSideB": true,
        "openEdgeA": false,
        "openEdgeB": false,
        "totalValue": 7,
        "isFaceUp": true,
        "next": null,
        "image": "http://localhost:8080/images/dom2.5.png",
    },
    {
        "index": 15,
        "sideA": 2,
        "sideB": 4,
        "isDouble": false,
        "edgeL": null,
        "edgeR": null,
        "isHorizontal": false,
        "openSideA": true,
        "openSideB": true,
        "openEdgeA": false,
        "openEdgeB": false,
        "totalValue": 6,
        "isFaceUp": true,
        "next": null,
        "image": "http://localhost:8080/images/dom2.4.png",
    },
    {
        "index": 14,
        "sideA": 2,
        "sideB": 3,
        "isDouble": false,
        "edgeL": null,
        "edgeR": null,
        "isHorizontal": false,
        "openSideA": true,
        "openSideB": true,
        "openEdgeA": false,
        "openEdgeB": false,
        "totalValue": 5,
        "isFaceUp": true,
        "next": null,
        "image": "http://localhost:8080/images/dom2.3.png",
    },
    {
        "index": 13,
        "sideA": 2,
        "sideB": 2,
        "isDouble": true,
        "edgeL": 4,
        "edgeR": 4,
        "isHorizontal": false,
        "openSideA": false,
        "openSideB": false,
        "openEdgeA": true,
        "openEdgeB": true,
        "totalValue": 4,
        "isFaceUp": true,
        "next": null,
        "image": "http://localhost:8080/images/dom2.2.png",
    },
    {
        "index": 12,
        "sideA": 1,
        "sideB": 6,
        "isDouble": false,
        "edgeL": null,
        "edgeR": null,
        "isHorizontal": false,
        "openSideA": true,
        "openSideB": true,
        "openEdgeA": false,
        "openEdgeB": false,
        "totalValue": 7,
        "isFaceUp": true,
        "next": null,
        "image": "http://localhost:8080/images/dom1.6.png",
    },
    {
        "index": 11,
        "sideA": 1,
        "sideB": 5,
        "isDouble": false,
        "edgeL": null,
        "edgeR": null,
        "isHorizontal": false,
        "openSideA": true,
        "openSideB": true,
        "openEdgeA": false,
        "openEdgeB": false,
        "totalValue": 6,
        "isFaceUp": true,
        "next": null,
        "image": "http://localhost:8080/images/dom1.5.png",
    },
    {
        "index": 10,
        "sideA": 1,
        "sideB": 4,
        "isDouble": false,
        "edgeL": null,
        "edgeR": null,
        "isHorizontal": false,
        "openSideA": true,
        "openSideB": true,
        "openEdgeA": false,
        "openEdgeB": false,
        "totalValue": 5,
        "isFaceUp": true,
        "next": null,
        "image": "http://localhost:8080/images/dom1.4.png",
    },
    {
        "index": 9,
        "sideA": 1,
        "sideB": 3,
        "isDouble": false,
        "edgeL": null,
        "edgeR": null,
        "isHorizontal": false,
        "openSideA": true,
        "openSideB": true,
        "openEdgeA": false,
        "openEdgeB": false,
        "totalValue": 4,
        "isFaceUp": true,
        "next": null,
        "image": "http://localhost:8080/images/dom1.3.png",
    },
    {
        "index": 8,
        "sideA": 1,
        "sideB": 2,
        "isDouble": false,
        "edgeL": null,
        "edgeR": null,
        "isHorizontal": false,
        "openSideA": true,
        "openSideB": true,
        "openEdgeA": false,
        "openEdgeB": false,
        "totalValue": 3,
        "isFaceUp": true,
        "next": null,
        "image": "http://localhost:8080/images/dom1.2.png",
    },
    {
        "index": 7,
        "sideA": 1,
        "sideB": 1,
        "isDouble": true,
        "edgeL": 2,
        "edgeR": 2,
        "isHorizontal": false,
        "openSideA": false,
        "openSideB": false,
        "openEdgeA": true,
        "openEdgeB": true,
        "totalValue": 2,
        "isFaceUp": true,
        "next": null,
        "image": "http://localhost:8080/images/dom1.1.png",
    },
    {
        "index": 6,
        "sideA": 0,
        "sideB": 6,
        "isDouble": false,
        "edgeL": null,
        "edgeR": null,
        "isHorizontal": false,
        "openSideA": true,
        "openSideB": true,
        "openEdgeA": false,
        "openEdgeB": false,
        "totalValue": 6,
        "isFaceUp": true,
        "next": null,
        "image": "http://localhost:8080/images/dom0.6.png",
    },
    {
        "index": 5,
        "sideA": 0,
        "sideB": 5,
        "isDouble": false,
        "edgeL": null,
        "edgeR": null,
        "isHorizontal": false,
        "openSideA": true,
        "openSideB": true,
        "openEdgeA": false,
        "openEdgeB": false,
        "totalValue": 5,
        "isFaceUp": true,
        "next": null,
        "image": "http://localhost:8080/images/dom0.5.png",
    },
    {
        "index": 4,
        "sideA": 0,
        "sideB": 4,
        "isDouble": false,
        "edgeL": null,
        "edgeR": null,
        "isHorizontal": false,
        "openSideA": true,
        "openSideB": true,
        "openEdgeA": false,
        "openEdgeB": false,
        "totalValue": 4,
        "isFaceUp": true,
        "next": null,
        "image": "http://localhost:8080/images/dom0.4.png",
    },
    {
        "index": 3,
        "sideA": 0,
        "sideB": 3,
        "isDouble": false,
        "edgeL": null,
        "edgeR": null,
        "isHorizontal": false,
        "openSideA": true,
        "openSideB": true,
        "openEdgeA": false,
        "openEdgeB": false,
        "totalValue": 3,
        "isFaceUp": true,
        "next": null,
        "image": "http://localhost:8080/images/dom0.3.png",
    },
    {
        "index": 2,
        "sideA": 0,
        "sideB": 2,
        "isDouble": false,
        "edgeL": null,
        "edgeR": null,
        "isHorizontal": false,
        "openSideA": true,
        "openSideB": true,
        "openEdgeA": false,
        "openEdgeB": false,
        "totalValue": 2,
        "isFaceUp": true,
        "next": null,
        "image": "http://localhost:8080/images/dom0.2.png",
    },
    {
        "index": 1,
        "sideA": 0,
        "sideB": 1,
        "isDouble": false,
        "edgeL": null,
        "edgeR": null,
        "isHorizontal": false,
        "openSideA": true,
        "openSideB": true,
        "openEdgeA": false,
        "openEdgeB": false,
        "totalValue": 1,
        "isFaceUp": true,
        "next": null,
        "image": "http://localhost:8080/images/dom0.1.png",
    },
    {
        "index": 0,
        "sideA": 0,
        "sideB": 0,
        "isDouble": true,
        "edgeL": 0,
        "edgeR": 0,
        "isHorizontal": false,
        "openSideA": false,
        "openSideB": false,
        "openEdgeA": true,
        "openEdgeB": true,
        "totalValue": 0,
        "isFaceUp": true,
        "next": null,
        "image": "http://localhost:8080/images/dom0.0.png",
    },

]

export default dominos
